name:                dans-kata
version:             0.1.0.0
github:              "tbsklg/dans-kata"
license:             BSD3
author:              "Tobias Klug"
maintainer:          "tbs.klg@gmail.com"
copyright:           "2022 Tobias Klug"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dans-kata#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  dans-kata-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dans-kata
    - containers

tests:
  dans-kata-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dans-kata
    - hspec == 2.7.10
    - QuickCheck == 2.14.2
    - HUnit == 1.6.2.0

